export const operatorsR6 = [
  {
    name: `Sledge`,
    portrait: `img/ops/Sledge.webp`,
    role: `Attacker`,
    ability: `Tactical Breaching Hammer`,
    specialty: `BREACH, ANTI-GADGET`,
  },
  {
    name: `Thatcher`,
    portrait: `img/ops/Thatcher.webp`,
    role: `Attacker`,
    ability: `EMP Grenade`,
    specialty: `Anti-Gadget, Support`,
  },
  {
    name: `Mute`,
    portrait: `img/ops/Mute.webp`,
    role: `Defender`,
    ability: `Signal Disruptor`,
    specialty: `ANTI-GADGET, CROWD CONTROL`,
  },
  {
    name: `Smoke`,
    portrait: `img/ops/Smoke.webp`,
    role: `Defender`,
    ability: `Remote Gas Grenade`,
    specialty: `ANTI-ENTRY, TRAPPER`,
  },
  {
    name: `Ash`,
    portrait: `img/ops/Ash.webp`,
    role: `Attacker`,
    ability: `Breaching Round`,
    specialty: `BREACH, FRONTLINE`,
  },
  {
    name: `Thermite`,
    portrait: `img/ops/Thermite.webp`,
    role: `Attacker`,
    ability: `Exothermic Charge`,
    specialty: `BREACH, SUPPORT`,
  },
  {
    name: `Castle`,
    portrait: `img/ops/Castle.webp`,
    role: `Defender`,
    ability: `Armor Panel`,
    specialty: `ANTI-ENTRY, SUPPORT`,
  },
  {
    name: `Pulse`,
    portrait: `img/ops/Pulse.webp`,
    role: `Defender`,
    ability: `Heartbeat Sensor`,
    specialty: `INTEL, SUPPORT`,
  },
  {
    name: `Twitch`,
    portrait: `img/ops/Twitch.webp`,
    role: `Attacker`,
    ability: `Shock Drone`,
    specialty: `ANTI-GADGET, INTEL`,
  },
  {
    name: `Montagne`,
    portrait: `img/ops/Montagne.webp`,
    role: `Attacker`,
    ability: `Extendable Shield`,
    specialty: `INTEL, SUPPORT`,
  },
  {
    name: `Doc`,
    portrait: `img/ops/Doc.webp`,
    role: `Defender`,
    ability: `Stim Pistol`,
    specialty: `SUPPORT`,
  },
  {
    name: `Rook`,
    portrait: `img/ops/Rook.webp`,
    role: `Defender`,
    ability: `Armor Pack`,
    specialty: `SUPPORT`,
  },
  {
    name: `Fuze`,
    portrait: `img/ops/Fuze.webp`,
    role: `Attacker`,
    ability: `Cluster Charge`,
    specialty: `ANTI-GADGET`,
  },
  {
    name: `Glaz`,
    portrait: `img/ops/Glaz.webp`,
    role: `Attacker`,
    ability: `HDS Flip Sight`,
    specialty: `INTEL, SUPPORT`,
  },
  {
    name: `Kapkan`,
    portrait: `img/ops/Kapkan.webp`,
    role: `Defender`,
    ability: `EDD`,
    specialty: `ANTI-ENTRY, TRAPPER`,
  },
  {
    name: `Tachanka`,
    portrait: `img/ops/Tachanka.webp`,
    role: `Defender`,
    ability: `Shumikha`,
    specialty: `ANTI-GADGET, CROWD CONTROL`,
  },
  {
    name: `IQ`,
    portrait: `img/ops/IQ.webp`,
    role: `Attacker`,
    ability: `ERD`,
    specialty: `INTEL, SUPPORT`,
  },
  {
    name: `Blitz`,
    portrait: `img/ops/Blitz.webp`,
    role: `Attacker`,
    ability: `G52-Tactical Shield`,
    specialty: `FRONTLINE, MAP CONTROL`,
  },
  {
    name: `Bandit`,
    portrait: `img/ops/Bandit.webp`,
    role: `Defender`,
    ability: `Shock Wire`,
    specialty: `ANTI-ENTRY, ANTI-GADGET`,
  },
  {
    name: `Jäger`,
    portrait: `img/ops/Jager.webp`,
    role: `Defender`,
    ability: `ADS`,
    specialty: `ANTI-GADGET, SUPPORT`,
  },
];
